### ISSUE TITLE
Error occurred while disabling UltraBar v2.1 - java.util.ConcurrentModificationException: null

### ISSUE THREAD

**Issue by mibby** [ryandw11/UltraBar#17]
```
[10:00:01] [Server thread/INFO]: [UltraBar] Disabling UltraBar v2.1
[10:00:01] [Server thread/ERROR]: Error occurred while disabling UltraBar v2.1 (Is it up to date?)
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909) ~[?:1.8.0_212]
	at java.util.ArrayList$Itr.next(ArrayList.java:859) ~[?:1.8.0_212]
	at me.ryandw11.ultrabar.core.UltraBar.onDisable(UltraBar.java:110) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.14.3.jar:git-Paper-134]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:373) ~[patched_1.14.3.jar:git-Paper-134]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:453) ~[patched_1.14.3.jar:git-Paper-134]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:439) ~[patched_1.14.3.jar:git-Paper-134]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:432) ~[patched_1.14.3.jar:git-Paper-134]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.disablePlugins(CraftServer.java:401) ~[patched_1.14.3.jar:git-Paper-134]
	at net.minecraft.server.v1_14_R1.MinecraftServer.stop(MinecraftServer.java:717) ~[patched_1.14.3.jar:git-Paper-134]
	at net.minecraft.server.v1_14_R1.DedicatedServer.stop(DedicatedServer.java:737) ~[patched_1.14.3.jar:git-Paper-134]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:949) ~[patched_1.14.3.jar:git-Paper-134]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by ryandw11** [comment]
Thanks for the report. I'll look into it.
