### ISSUE TITLE
Error When running Plugin

### ISSUE THREAD

**Issue by AudaxiaEB** [ryandw11/UltraBar#20]
[12:13:49] [Server thread/WARN]: [UltraBar] Task #54 for UltraBar v2.1.2 generated an exception
java.lang.IllegalArgumentException: Progress must be between 0.0 and 1.0 (1.05)
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191) ~[patched_1.14.4.jar:git-Paper-146]
	at org.bukkit.craftbukkit.v1_14_R1.boss.CraftBossBar.setProgress(CraftBossBar.java:158) ~[patched_1.14.4.jar:git-Paper-146]
	at me.ryandw11.ultrabar.BossBarSced.run(BossBarSced.java:136) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-146]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-146]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1147) ~[patched_1.14.4.jar:git-Paper-146]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420) ~[patched_1.14.4.jar:git-Paper-146]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1074) ~[patched_1.14.4.jar:git-Paper-146]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:918) ~[patched_1.14.4.jar:git-Paper-146]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]

**Comment by ryandw11** [comment]
Can I see your config?

**Comment by AudaxiaEB** [comment]
Problem literally magically fixed itself out of nowhere no idea what caused it but It doesn't seem to be returning! Thanks for the super quick response btw!
