### ISSUE TITLE
How do I resolve this?

### ISSUE THREAD

**Issue by DumplingSaint** [ryandw11/UltraBar#25]
[18:57:03 WARN]: [UltraBar] Task #4465507 for UltraBar v2.2 generated an exception
java.lang.IllegalArgumentException: Progress must be between 0.0 and 1.0 (1.05)
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191) ~[patched_1.15.2.jar:git-Paper-371]
at org.bukkit.craftbukkit.v1_15_R1.boss.CraftBossBar.setProgress(CraftBossBar.java:158) ~[patched_1.15.2.jar:git-Paper-371]
at me.ryandw11.ultrabar.BossBarSced.run(BossBarSced.java:136) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.15.2.jar:git-Paper-371]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.15.2.jar:git-Paper-371]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1264) ~[patched_1.15.2.jar:git-Paper-371]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431) ~[patched_1.15.2.jar:git-Paper-371]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1181) ~[patched_1.15.2.jar:git-Paper-371]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:970) ~[patched_1.15.2.jar:git-Paper-371]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

**Comment by ryandw11** [comment]
Can I see your config or the command you ran? It looks like you set the progress on one of the bars to be less that 0.0 or greater than 1.0. For reference 0.5 is 50% full.

**Comment by DumplingSaint** [comment]
Here is what I changed

  Number_Of_Messages: 1
  '1':
    Message: '&b&lMCVantage.Net'
    Color: blue
    Style: '1'
    Time: -1

Here is the complete config
# 
#                        UltraBar                          #
bstats: true
update_checker: true
OnJoin:
  BossBar:
    Enabled: false
    Message: '&6Welcome Back &5{player}&6!'
    Color: green
    Time: 10
    Style: '6'
    Health: 1
  Title:
    Enabled: false
    Message: '&6Welcome Back &5{player}&6'
    SubTitle: '&bto the best server ever!'
    fadein: 5
    fadeout: 5
    time: 20
  ActionBar:
    Enabled: fase
    Message: '&6Welcome Back &5{player}&6!'
OnDeath:
  BossBar:
    Enabled: false
    Message: '&6Welcome Back &5{player}&6!'
    Color: green
    Time: 10
    Style: '6'
    Health: 1
  Title:
    Enabled: false
    Message: '&6Welcome Back &5{player}&6'
    SubTitle: '&bto the best server ever!'
    fadein: 5
    fadeout: 5
    time: 20
  ActionBar:
    Enabled: false
    Message: '&6Welcome Back &5{player}&6!'
OnCommand:
  list:
  - examplecmd
  examplecmd:
    BossBar:
      Message: '&6You ran a command!'
      Color: green
      Time: 10
      Style: '6'
      Health: 1
    ActionBar:
      Message: '&6ActionBars can be used&6!'
    Title:
      Message: '&6Along with titles.&6'
      SubTitle: '&bThese support placeholderapi!'
      fadein: 5
      fadeout: 5
      time: 20
BossBarMessages:
  '2':
    Message: '&2BossBar #2'
    Color: blue
    Style: '6'
    Time: 10
  '3':
    Message: '&3BossBar #3'
    Color: red
    Style: '6'
    Time: 10
  Enabled: true
  World_Whitelist_Enabled: false
  Random_Order: false
  World_Whitelist:
  - world
  Number_Of_Messages: 1
  '1':
    Message: '&b&lMCVantage.Net'
    Color: blue
    Style: '1'
    Time: -1
Title_Announcements:
  Enabled: false
  Random_Order: false
  Number_Of_Messages: 3
  Time: 20
  '1':
    Message: '&6Message 1&6'
    SubTitle: '&bMeassage 1'
    fadein: 5
    fadeout: 5
    time: 20
  '2':
    Message: '&6Message 2&6'
    SubTitle: '&bMessage 2'
    fadein: 5
    fadeout: 5
    time: 20
  '3':
    Message: '&6Message 3&6'
    SubTitle: '&bMessage 3'
    fadein: 5
    fadeout: 5
    time: 20
Action_Announcements:
  Enabled: false
  Random_Order: false
  Number_Of_Messages: 3
  Time: 10
  '1':
    Message: Message 1
  '2':
    Message: Message 2
  '3':
    Message: Message 3
WorldGuardRegion:
  Enabled: true
  Message: '&6<< &b%region% &6>>'
  Message2: '&b%region% &3<<>> &6and &c%number%&6 more.'

**Comment by DumplingSaint** [comment]
Fixed it by setting time to 0 instead of -1. You might wanna specify what you told me in the context to idiot-proof it.
