### ISSUE TITLE
Could not pass event PlayerJoinEvent to UltraBar

### ISSUE THREAD

**Issue by mibby** [ryandw11/UltraBar#3]
Downgrading to UltraBar v1.4.9, everything is fine.

```
[06:45:43] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to UltraBar v1.5.1.1
org.bukkit.event.EventException: null
    at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1509]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1509]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1509]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:527) ~[patched_1.12.2.jar:git-Paper-1509]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:512) ~[patched_1.12.2.jar:git-Paper-1509]
    at net.minecraft.server.v1_12_R1.PlayerList.onPlayerJoin(PlayerList.java:370) ~[patched_1.12.2.jar:git-Paper-1509]
    at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:183) ~[patched_1.12.2.jar:git-Paper-1509]
    at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:178) ~[patched_1.12.2.jar:git-Paper-1509]
    at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:68) ~[patched_1.12.2.jar:git-Paper-1509]
    at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:255) ~[patched_1.12.2.jar:git-Paper-1509]
    at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:150) ~[patched_1.12.2.jar:git-Paper-1509]
    at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:947) ~[patched_1.12.2.jar:git-Paper-1509]
    at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1509]
    at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:773) ~[patched_1.12.2.jar:git-Paper-1509]
    at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) ~[patched_1.12.2.jar:git-Paper-1509]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
    at me.ryandw11.ultrabar.listener.OnJoin.onJoin(OnJoin.java:61) ~[?:?]
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor564.execute(Unknown Source) ~[?:?]
    at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1509]
    ... 15 more
```

Config
```
#
#                        UltraBar                          #
bstats: false
WorldGuardRegion:
  Enabled: false
  Message: '&6<< &b%region% &6>>'
  Message2: '&b%region% &3<<>> &6and &c%number%&6 more.'
OnJoin:
  BossBar:
    Enabled: false
    Message: '&6Welcome Back &5{player}&6!'
    Color: green
    Time: 10
    Style: '6'
    Health: 1
  Title:
    Enabled: false
    Message: '&6Welcome Back &5{player}&6'
    SubTitle: '&bto the best server ever!'
    fadein: 5
    fadeout: 5
    time: 20
  ActionBar:
    Enabled: false
    Message: '&6Welcome Back &5{player}&6!'
  BossBarMessages:
    Enabled: false
    Time: 10
    Number_Of_Messages: 3
    '1':
      Message: '&1BossBar #1'
      Color: green
      Style: '6'
    '2':
      Message: '&2BossBar #2'
      Color: blue
      Style: '6'
    '3':
      Message: '&3BossBar #3'
      Color: red
      Style: '6'
BossBarMessages:
  Enabled: true
  World_Whitelist_Enabled: false
  Random_Order: false
  World_Whitelist:
  - world
  Number_Of_Messages: 3
  '1':
    Message: '&1BossBar #1'
    Color: green
    Style: '6'
    Time: 10
  '2':
    Message: '&2BossBar #2'
    Color: blue
    Style: '6'
    Time: 10
  '3':
    Message: '&3BossBar #3'
    Color: red
    Style: '6'
    Time: 10
 ```

**Comment by ryandw11** [comment]
Fixed in 1.5.1.2. Thanks for reporting.
