### ISSUE TITLE
Error occurred while disabling UltraBar v2.3.1

### ISSUE THREAD

**Issue by SrBedrock** [ryandw11/UltraBar#37]
```
[20:34:08 INFO]: [UltraBar] Saving tracked bars to file.
[20:34:08 INFO]: [UltraBar] Save complete!
[20:34:08 ERROR]: Error occurred while disabling UltraBar v2.3.1 (Is it up to date?)
java.lang.NullPointerException: null
        at me.ryandw11.ultrabar.UltraBar.onDisable(UltraBar.java:151) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.5.jar:git-Airplane-"f74d161"]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:405) ~[patched_1.16.5.jar:git-Airplane-"f74d161"]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:533) ~[patched_1.16.5.jar:git-Airplane-"f74d161"]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:519) ~[patched_1.16.5.jar:git-Airplane-"f74d161"]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:512) ~[patched_1.16.5.jar:git-Airplane-"f74d161"]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.disablePlugins(CraftServer.java:452) ~[patched_1.16.5.jar:git-Airplane-"f74d161"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.stop(MinecraftServer.java:903) ~[patched_1.16.5.jar:git-Airplane-"f74d161"]
        at net.minecraft.server.v1_16_R3.DedicatedServer.stop(DedicatedServer.java:766) ~[patched_1.16.5.jar:git-Airplane-"f74d161"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1181) ~[patched_1.16.5.jar:git-Airplane-"f74d161"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:292) ~[patched_1.16.5.jar:git-Airplane-"f74d161"]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by mibby** [comment]
@ryandw11 Do you happen to have a CI build server for dev builds? Would like to test (and have) the fix but running into various compilation errors.

**Comment by ryandw11** [comment]
I do not have a build server right now. Here is a dev build if you want it: [REDACTED]

I need to upload it to spigot soon anyways.

As for the compilation errors, be sure you have built all of the required Spigot version from buildtools.

Edit: You can now download UltraBar builds from my build server. [ci.ryandw11.com](https://ci.ryandw11.com/job/ultra-bar/)
