### ISSUE TITLE
NullPointerException: null on shutdown

### ISSUE THREAD

**Issue by mibby** [ryandw11/UltraBar#4]
Downgrading to UltraBar v1.4.9, everything is fine.

```
[06:43:50] [Server thread/INFO]: [UltraBar] Disabling UltraBar v1.5.1.1
[06:43:50] [Server thread/ERROR]: Error occurred while disabling UltraBar v1.5.1.1 (Is it up to date?)
java.lang.NullPointerException: null
    at me.ryandw11.ultrabar.core.UltraBar.onDisable(UltraBar.java:99) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[patched_1.12.2.jar:git-Paper-1509]
    at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:350) ~[patched_1.12.2.jar:git-Paper-1509]
    at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:437) ~[patched_1.12.2.jar:git-Paper-1509]
    at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:424) ~[patched_1.12.2.jar:git-Paper-1509]
    at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417) ~[patched_1.12.2.jar:git-Paper-1509]
    at org.bukkit.craftbukkit.v1_12_R1.CraftServer.disablePlugins(CraftServer.java:363) ~[patched_1.12.2.jar:git-Paper-1509]
    at net.minecraft.server.v1_12_R1.MinecraftServer.stop(MinecraftServer.java:486) ~[patched_1.12.2.jar:git-Paper-1509]
    at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:701) ~[patched_1.12.2.jar:git-Paper-1509]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
 ```

Config
```
#
#                        UltraBar                          #
bstats: false
WorldGuardRegion:
  Enabled: false
  Message: '&6<< &b%region% &6>>'
  Message2: '&b%region% &3<<>> &6and &c%number%&6 more.'
OnJoin:
  BossBar:
    Enabled: false
    Message: '&6Welcome Back &5{player}&6!'
    Color: green
    Time: 10
    Style: '6'
    Health: 1
  Title:
    Enabled: false
    Message: '&6Welcome Back &5{player}&6'
    SubTitle: '&bto the best server ever!'
    fadein: 5
    fadeout: 5
    time: 20
  ActionBar:
    Enabled: false
    Message: '&6Welcome Back &5{player}&6!'
  BossBarMessages:
    Enabled: false
    Time: 10
    Number_Of_Messages: 3
    '1':
      Message: '&1BossBar #1'
      Color: green
      Style: '6'
    '2':
      Message: '&2BossBar #2'
      Color: blue
      Style: '6'
    '3':
      Message: '&3BossBar #3'
      Color: red
      Style: '6'
BossBarMessages:
  Enabled: true
  World_Whitelist_Enabled: false
  Random_Order: false
  World_Whitelist:
  - world
  Number_Of_Messages: 3
  '1':
    Message: '&1BossBar #1'
    Color: green
    Style: '6'
    Time: 10
  '2':
    Message: '&2BossBar #2'
    Color: blue
    Style: '6'
    Time: 10
  '3':
    Message: '&3BossBar #3'
    Color: red
    Style: '6'
    Time: 10
 ```

**Comment by ryandw11** [comment]
Fixed in version 1.5.1.2. Thanks for reporting.
