### ISSUE TITLE
I can't use your plugin?

### ISSUE THREAD

**Issue by Bin006** [ryandw11/UltraBar#41]
![image](https://user-images.githubusercontent.com/51014176/135647107-1b259842-c728-483a-a3dd-7d1d5d72ff19.png)

**Comment by Bin006** [comment]
[22:35:36] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'ultrabar' in plugin UltraBar v2.3.1.1
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[Spigot.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[Spigot.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[Spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1399) [Spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1234) [Spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [Spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [Spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot.jar:git-Spigot-dcd1643-e60fc34]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_301]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_301]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [Spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [Spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [Spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [Spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [Spigot.jar:git-Spigot-dcd1643-e60fc34]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_301]
Caused by: java.lang.NoSuchMethodError: org.bukkit.Bukkit.createBossBar(Lorg/bukkit/NamespacedKey;Ljava/lang/String;Lorg/bukkit/boss/BarColor;Lorg/bukkit/boss/BarStyle;[Lorg/bukkit/boss/BarFlag;)Lorg/bukkit/boss/KeyedBossBar;
	at me.ryandw11.ultrabar.announcements.IndividualBossBarAnnouncer.createBossBar(IndividualBossBarAnnouncer.java:127) ~[?:?]
	at me.ryandw11.ultrabar.announcements.IndividualBossBarAnnouncer.<init>(IndividualBossBarAnnouncer.java:61) ~[?:?]
	at me.ryandw11.ultrabar.UltraBar.resetBarAnnouncer(UltraBar.java:340) ~[?:?]
	at me.ryandw11.ultrabar.commands.UltraBarCommand.onCommand(UltraBarCommand.java:64) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[Spigot.jar:git-Spigot-dcd1643-e60fc34]
	... 15 more

**Comment by Bin006** [comment]
@ryandw11 how to fix?

**Comment by ryandw11** [comment]
I've fixed the issue. You can download the fix here: https://ci.ryandw11.com/job/ultra-bar/.

It will be included in the next update on Spigot too.
