### ISSUE TITLE
Plugin disables itself for no reason

### ISSUE THREAD

**Issue by nixybuilder** [ryandw11/UltraBar#48]
Hello, i have issues on 1.21 with the plugin because it randomly disables it and i cant send any command like /bar

I dont know what to do, its the only plugin that barely works on 1.21...

[10:09:52] [Server thread/WARN]: Unexpected exception while parsing console command "bar"
org.bukkit.command.CommandException: Cannot execute command 'bar' in plugin UltraBar v2.3.2.1 - plugin is disabled.
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:165) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:1000) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at org.bukkit.craftbukkit.CraftServer.dispatchServerCommand(CraftServer.java:985) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:526) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:474) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1598) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-130-b1b5d4c]
	at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]

**Comment by ryandw11** [comment]
That likely means the plugin encountered an issue during the startup process. Can you find an error message from UltraBar earlier in the logs?

**Comment by nixybuilder** [comment]
![image](https://github.com/user-attachments/assets/8a45d7c6-5740-4cea-b73f-3ed6183fcb9e)
i see this, could you explain what it means more? i dont get it

**Comment by ryandw11** [comment]
That means that you are using a player specific placeholder on a server wide message, like health for example.

**Comment by nixybuilder** [comment]
so this is not fine..?

Message: '&f &f%player_current_exp% / &f%player_exp_to_level%    %vault_eco_balance%   &f
        %gemseconomy_balance_gem%'

**Comment by nixybuilder** [comment]
its strange it disabled itself after the 1k seconds i put in the config. No issue with player placeholders.

**Comment by ryandw11** [comment]
Can you show that section of the config with the 1k seconds?

**Comment by nixybuilder** [comment]
mb it was 100 sec but heres the whole config ignore the name since the paste gen it itself https://paste.sparked.host/noticexowu.yaml

**Comment by nixybuilder** [comment]
i couldnt find way to not switch them. when i only put there one line it made the other 2 itself -_- so i just duplicated them to all 3 but i still dont get it it disabled cuz i cant use player placeholders even tho they work no issue before it just crashes

**Comment by nixybuilder** [comment]
A plugin gemseconomy, placeholder was doing that
